name: CI
on: [push, pull_request]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: foundry-toolchain
        uses: foundry-rs/foundry-toolchain@v1.0.6
