name: CI
on: [push, pull_request]

jobs:

  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: intall-foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: install
        run: forge install
      - name: test
        run: forge test -vvv

  lint:
    name: lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use node@12
        uses: actions/setup-node@v1
        with: { node-version: '12.x' }

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-v1-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-v1

      - name: install
        run: yarn --prefer-offline

      - name: prettier
        run: yarn prettier:check
